language: go

go:
  - 1.6
  - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script: 
  - golint ./...
  - go vet ./...
  - go test -v -parallel 10 -covermode=count -coverprofile=main.coverage.out -coverpkg=./
  - go test -v -parallel 10 -covermode=count -coverprofile=graph.coverage.out -coverpkg=./graph
  - go test -v -parallel 10 -covermode=count -coverprofile=util.coverage.out -coverpkg=./util
  - go test -v -parallel 10 -covermode=count -coverprofile=backends.coverage.out -coverpkg=./backends
  - cat *.coverage.out | grep -v "mode: count" >> coverage.out
  - cat coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken WVURXfIfQnohf4flfYJfa3haa9hwGwhU2
