language: go

go:
  - 1.6
  - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script: 
  - golint ./...
  - go vet ./...
  - go test -v -parallel 10 -covermode=count -coverprofile=coverage.out -coverpkg=./... main
#  - echo "mode: set" > coverage.out && cat *.cover.out | grep -v mode: | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken WVURXfIfQnohf4flfYJfa3haa9hwGwhU2
